import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Portfolio - Ninh Nam Web Dev',
    description: 'A portfolio Generated by Next.JS',
    creator: 'Ninh Nam Web Dev',
    generator: 'Portfolio - Ninh Nam Web Dev',
    applicationName: 'Portfolio - Ninh Nam Web Dev',
    referrer: 'origin-when-cross-origin',
    keywords: [
        'Ninh Nam',
        'React',
        'JavaScript',
        'NextJS',
        'Portfolio of Ninh Nam',
        'Ninh Nam Web Dev'
    ],
    openGraph: {
        images: '/images/logo.png'
    }
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    );
}
